//This file was generated by script swreg2regmap.py

//register address mapping
#define NK 0
#define XX 1
#define YY 2
#define DATA_X 3
#define DATA_Y 4
#define DATA_LABEL 5
#define CONTROL 6
#define XLABEL 7
