//This file was generated by script swreg2regmap.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define XX 2
#define YY 3
#define DATA_X 4
#define DATA_Y 5
#define DATA_LABEL 6
#define NLABELS 7
#define CLASSIFY 8
#define D_READY 9
#define XLABEL 10
#define DISTANCE 11
